{% set version = "5.2.0" %}

package:
  name: jupyter_console
  version: {{ version }}

source:
  fn: jupyter_console-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/j/jupyter_console/jupyter_console-{{ version }}.tar.gz
  sha256: 545dedd3aaaa355148093c5609f0229aeb121b4852995c2accfa64fe3e0e55cd

build:
  number: 0
  script: python -m pip install --no-deps .
  entry_points:
    - jupyter-console = jupyter_console.app:main

requirements:
  build:
    - python
    - pip
  run:
    - python
    - jupyter_client
    - ipython
    - ipykernel
    - prompt_toolkit <2.0.0,>=1.0.0
    - pygments
    - pexpect  # [not win]

test:
  commands:
    - jupyter-console -h
  imports:
    - jupyter_console

about:
  home: http://jupyter.org
  license: BSD 3-Clause
  summary: Jupyter terminal console

extra:
  recipe-maintainers:
    - jakirkham
    - minrk
    - pelson
    - takluyver
    - ocefpaf
