travis:
  secure:
    BINSTAR_TOKEN: mSSFIYs1z/W+mqCfx6gU/BbN69/YkZM3/y8Fxw9ETnyWDZ4kSc5ulJan/BElQKfNIOOSUoszjcNEIt4/OhqlXQbaS6EcWRXuCnCSLE7HBWDf4UeHrm4tkEtJOD0zYAiXhTvgok/ATUYRXgLR+jGcanFdWuMalCfqXPfYuEUdOyeU1Ug/86emK/9vaTPxa421ql4HO6G853Y/pbr9er+IpiBJwAc9JOcN1P2omQAjMls5vP48ElfloELN2xq+fVa2NJdA90dr14aatbquHBWzSNK8fS0cUX7+M/w3dMBRDI0dEZV5HkeCRWZsofAr5pHPhGJm7ncbmAkL3fAltdQJt/OSZODVm1312AARAn2nA4boHJSHFOcABgUteWPPHWqa3C6EMF57kOraT2pNcPTk8mcgZSgnGEPmtJ4hV/boDF7P19yOXOdGI/W8syn0rbbi5HlN6ISic9QvDPX2tJn35mRGNyWZ4NcPMy7s5LnVx1AkteA8K4B8ebIr+3aV3tXbnrYXFcH8LURMuzzrRcrWd1gXFyRsYye9daqX/bC1osrjY54uKPE/GG0Ui++4NXTdikPX1QEabVzw6iARQH02Fho0ZHWzX8XCd7ca9Ra84UI5smentaqyV3jToTc1jz0325f24EdEOXQT74byqhFDQYit/TuocfwZPvXyO7mf0eo=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
