travis:
  secure:
    BINSTAR_TOKEN: EnfB9uNHTmzrxZTnnLHTnT1L7+NjhGBJJes+iUabTbO/j7uGMVseIXEMfBSmFWJfQFnTumwXj49Qq7tGtiFvNy5AbSGfiLwPP5X8g1mB0MqgNeakQfNwVhcqhNQK733wYFs6CbOuLGqFjHB/xsYiOSVTJ7hu7O7oFPxENrMHriwB9EJH6Gb4KRIZeAiYOIpRt2FpbdlQOfX3KBaGnqfgtvInRsef7GI+yUXWI0/oQNhLrHkPGOMINdTvfXl4Z8qwFbxCL3yEBKlbgEKD6pnKaIEtcDc+oTUTuNFh3sScxUrW/NoD4INRf5cfFDsPg+xpJdKE1hnrGwJC0Eur9h93OfgI/hYj7QIPYQoIKu1a5doW+s6uRVc/jVOGi5piADRX/j/6dfwWMS/gA58p3tRtihma5nnWHNARqbMXmFAeC0i6zpS1hlTkalGsbPR5xSLKbSE65jpajSdJnXFhTgHYi/MVsqGPi9Kr3h0Lec8rmHBa0u9iQkhE77gUffyTbLXaOfjv/MM+CL43ss976VzsPZSXM9l3tkpGF5aVaZ5mi5iV7Fqwg7q5+wM0qAa9Y1/CvkyhwttssUn1u46Bch29b8uCuGMpQxtCliEIXv/ciBoIptMR3HgyezgFEFmIVsbz8TNvtyUow5fMiq3NWI33eKKlZ0uQDZmymS51/7VdyUE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
